#!/usr/bin/bash

# Define the path to the packages list file
packages=./packages.txt

# Check if the packages list file exists
if [[ ! -f $packages ]]; then
    echo "Packages list $packages not found"
    exit 1
fi

# Loop through each package listed in the packages.txt file
for package in $(cat $packages); do
    # Check if the package is already installed using pacman
    if pacman -Qs "$package" > /dev/null; then
        echo "$package is already installed"
    else
        # Install the package if it is not already installed
        echo "Installing $package"
        pacman -Syu --noconfirm "$package"
    fi
done
~
